version: "3.6"
services:
    client:
        image: mrzdtydlntm/portomirza
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certbot/conf:/etc/letsencrypt:rw
            - ./certbot/www:/var/www/certbot:rw
            - ./default.conf:/etc/nginx/conf.d/default.conf
    certbot:
        image: certbot/certbot:latest
        container_name: certbot
        command: certonly --webroot --webroot-path=/var/www/certbot --email abu.amr.mrz@gmail.com --agree-tos --no-eff-email -d mrzdtydlntm.my.id  -d www.mrzdtydlntm.my.id
        volumes:
            - ./certbot/conf:/etc/letsencrypt:rw
            - ./certbot/www:/var/www/certbot:rw
            - ./certbot/logs:/var/log:rw
        depends_on:
            - client
